FROM python:3.12-slim

WORKDIR /app

COPY . .

RUN pip install -r requirements.txt

EXPOSE 9090

CMD ["uvicorn", "app_test:test", "--host", "0.0.0.0", "--port", "9090","--ssl-keyfile=/run/secrets/key","--ssl-certfile=/run/secrets/cert"]