FROM python:3.12-slim

WORKDIR /app

COPY . .

RUN pip install -r requirements.txt

EXPOSE 5000

CMD ["uvicorn", "app:test", "--host", "0.0.0.0", "--port", "9090","--ssl-keyfile=/run/secrets/app_key","--ssl-certfile=/run/secrets/app_cert"]