FROM python:3.12-alpine

WORKDIR /app
RUN apk add curl
COPY ./requirements.txt /tmp
RUN pip install -r /tmp/requirements.txt
COPY . .
EXPOSE 9190

CMD ["uvicorn", "app_test:test", "--host", "0.0.0.0", "--port", "9190","--ssl-keyfile=/run/secrets/key","--ssl-certfile=/run/secrets/cert"]
