services:
    distro:
        build:
            context: service
            dockerfile: Dockerfile_test
        depends_on:
            - gacha_db
        ports:
            - 9190:9190
        secrets:
            - cert
            - key
            - pw
            - jwt_private_key
            - jwt_public_key
        networks:
            - gacha_network

    gacha_db:
        image: mongo:latest
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_DATABASE: admin
            MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/pw
        command: mongod --quiet --logpath /dev/null
            --tlsAllowConnectionsWithoutCertificates
            --tlsMode preferTLS
            --tlsCertificateKeyFile /run/secrets/cert_db
            --tlsCAFile /run/secrets/cert_db
        secrets:
            - cert_db
            - pw
        tmpfs:
            - /data/db
        networks:
            - gacha_network

    newman:
        image: postman/newman:latest
        container_name: distro_service_tests
        restart: no
        depends_on:
            - distro
        entrypoint:
            [
                "newman",
                "run",
                "/etc/postman/gacha_unit.postman_collection.json",
                "--delay-request",
                "100",
                "--insecure",
                "--reporters",
                "cli",
            ]
        volumes:
            - ./tests/:/etc/postman
        networks:
            - gacha_network

secrets:
    pw:
        file: ./service/secrets/pw.txt
    cert:
        file: ./service/secrets/cert.pem
    key:
        file: ./service/secrets/key.pem
    cert_db:
        file: ./service/secrets/server.pem
    jwt_private_key:
        file: ./service/secrets/private.pem
    jwt_public_key:
        file: ./service/secrets/public.pem

networks:
    gacha_network:
        driver: bridge
