services:
  distro:
    build: 
      context: service
      dockerfile: Dockerfile_test
    depends_on:
      - db
    ports:
      - 9190:9190
    secrets:
      - cert
      - key
      - pw
      - jwt_private_key
      - jwt_public_key

  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/pw
    command: mongod --quiet --logpath /dev/null 
      --tlsAllowConnectionsWithoutCertificates
      --tlsMode preferTLS
      --tlsCertificateKeyFile /run/secrets/cert_db
      --tlsCAFile /run/secrets/cert_db
    secrets:
      - cert_db
      - pw
    volumes:
      - dbdata:/data/db
   
secrets: 
  pw: 
    file: ./service/secrets/pw.txt
  cert: 
    file: ./service/secrets/cert.pem
  key: 
    file: ./service/secrets/key.pem
  cert_db: 
    file: ./service/secrets/server.pem
  jwt_private_key:
    file: ./service/secrets/private.pem
  jwt_public_key:
    file: ./service/secrets/public.pem

  volumes:
    dbdata:
#services:
#  distro:
#    build: ./service
#    depends_on:
#      - db
#    ports:
#      - 5000:5000
#
#  db:
#    image: mongo:latest
#    ports:
#      - '27017:27017'
#    volumes:
#      - dbdata:/data/db
#    command: mongod --quiet --logpath /dev/null 
#
#volumes:
#  dbdata: