services:
  authentication:
    container_name: authentication
    restart: always
    build:
      context: ./service
    environment:
      - RESOURCE_PATH=/code/service/resources
    ports:
      - 9090:9090
    volumes:
      - ${PWD}/service:/code/service
    networks:
      - gacha_network
  db:
    container_name: db_authentication
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    command: mongod --quiet --logpath /dev/null 
    networks:
      - gacha_network

volumes:
  dbdata:
  
networks:
  gacha_network:
    driver: bridge
