services:
    authentication:
        container_name: authentication
        restart: always
        build:
            context: ./service
        environment:
            - RESOURCE_PATH=/code/service/resources
        ports:
            - 9090:9090
        volumes:
            - ${PWD}/service:/code/service
        networks:
            - gacha_network
        depends_on:
            - db
        secrets:
            - jwt_private_key
            - jwt_public_key
            - admin_account
            - ssl_private_key
            - ssl_cert

    db:
        container_name: db_authentication
        image: mongo:latest
        ports:
            - '27017:27017'
        volumes:
            - dbdata:/data/db
        command: mongod --quiet --logpath /dev/null
        networks:
            - gacha_network

volumes:
    dbdata:

secrets:
    jwt_private_key:
        file: ./service/secrets/private.pem
    jwt_public_key:
        file: ./service/secrets/public.pem
    ssl_private_key:
        file: ./service/secrets/key.pem
    ssl_cert:
        file: ./service/secrets/cert.pem
    admin_account:
        file: ./service/secrets/admin_account.json


networks:
    gacha_network:
        driver: bridge
