services:
  auction:
      build:
        context: ./service
        dockerfile: Dockerfile_test

      ports:
        - 9390:9390
      secrets:
        - auction_pw
        - auction_cert
        - auction_key
        - jwt_private_key
        - jwt_public_key
        - admin_account

secrets:
    auction_pw:
        file: ./service/secrets/pw.txt
    auction_cert:
        file: ./service/secrets/cert.pem
    auction_key:
        file: ./service/secrets/key.pem
    jwt_private_key:
        file: ./service/secrets/private.pem
    jwt_public_key:
        file: ./service/secrets/public.pem
    admin_account:
        file: ./service/secrets/admin_account.json
