services:
    auction:
        build:
            context: ./service
            dockerfile: Dockerfile_test
        healthcheck:
            test: curl --silent --fail --insecure https://localhost:9390/docs || exit 1
            interval: 5s
            retries: 3
            start_period: 5s
            timeout: 5s
        depends_on:
            - auction_db
        ports:
            - 9390:9390
        secrets:
            - auction_pw
            - auction_cert
            - auction_key
            - jwt_private_key
            - jwt_public_key
            - admin_account
        networks:
            - gacha_network

    auction_db:
        image: mongo:latest
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_DATABASE: admin
            MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/auction_pw
        command: mongod --quiet --logpath /dev/null
            --tlsAllowConnectionsWithoutCertificates
            --tlsMode preferTLS
            --tlsCertificateKeyFile /run/secrets/cert_db
            --tlsCAFile /run/secrets/cert_db
        secrets:
            - cert_db
            - auction_pw
        tmpfs:
            - /data/db
        networks:
            - gacha_network

    newman:
        image: postman/newman:latest
        container_name: auction_service_tests
        restart: no
        depends_on:
            auction:
                condition: service_healthy
        entrypoint:
            [
                "newman",
                "run",
                "/etc/postman/auction_unit.postman_collection.json",
                "--delay-request",
                "100",
                "--insecure",
                "--reporters",
                "cli",
            ]
        volumes:
            - ./tests/:/etc/postman
        networks:
            - gacha_network

secrets:
    auction_pw:
        file: ./service/secrets/pw.txt
    auction_cert:
        file: ./service/secrets/cert.pem
    cert_db:
        file: ./service/secrets/server.pem
    auction_key:
        file: ./service/secrets/key.pem
    jwt_private_key:
        file: ./service/secrets/private.pem
    jwt_public_key:
        file: ./service/secrets/public.pem
    admin_account:
        file: ./service/secrets/admin_account.json

networks:
  gacha_network:
    driver: bridge