services:
  auction:
    build:
      context: service
      dockerfile: Dockerfile
    depends_on:
      - auction_db
    ports:
      - 9390:9390
    secrets:
      - admin_account
      - auction_cert
      - auction_key
      - auction_pw
      - jwt_private_key
      - jwt_public_key

  auction_db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/auction_pw
    command: mongod --quiet --logpath /dev/null
      --tlsAllowConnectionsWithoutCertificates
      --tlsMode preferTLS
      --tlsCertificateKeyFile /run/secrets/cert_db
      --tlsCAFile /run/secrets/cert_db
    secrets:
      - cert_db
      - auction_pw
    tmpfs:
      - /data/db

secrets:
  admin_account:
    file: ./service/secrets/admin_account.json
  auction_pw:
    file: ./service/secrets/pw.txt
  auction_cert:
    file: ./service/secrets/cert.pem
  auction_key:
    file: ./service/secrets/key.pem
  cert_db:
    file: ./service/secrets/server.pem
  jwt_private_key:
    file: ./service/secrets/private.pem
  jwt_public_key:
    file: ./service/secrets/public.pem
