services:
  distro:
    build: 
      context: service
      dockerfile: Dockerfile_test
    depends_on:
      - db
    ports:
      - 9090:9090
    secrets:
      - app_cert
      - app_key
      - pw
      - jwt_private_key
      - jwt_public_key

  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/pw
    command: mongod --quiet --logpath /dev/null 
      --tlsAllowConnectionsWithoutCertificates
      --tlsMode preferTLS
      --tlsCertificateKeyFile /run/secrets/cert_db
      --tlsCAFile /run/secrets/cert_db
    secrets:
      - db_cert
      - pw
    tmpfs:
      - /data/db 
   
secrets: 
  #app_secrets
  app_cert: 
    file: ./service/secrets/app_cert.pem
  app_key: 
    file: ./service/secrets/app_key.pem
  
  #db_secrets
  db_cert: 
    file: ./service/secrets/db.pem
  pw: 
    file: ./service/secrets/pw.txt
  
  #jwt_secrets
  jwt_private_key:
    file: ./service/secrets/jwt_private_key.pem
  jwt_public_key:
    file: ./service/secrets/jwt_public_key.pem
  
  volumes:
    dbdata:
