# services:
#   auction:
#     build: 
#       context: service
#       dockerfile: Dockerfile_test 
#     depends_on:
#       - db
#     ports:
#       - 9090:9090
#     secrets:
#       - cert
#       - key
#       - pw
#       - jwt_private_key
#       - jwt_public_key

#   db:
#     image: mongo:latest
#     ports:
#       - '27017:27017'
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_DATABASE: admin
#       MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/pw
#     command: mongod --quiet --logpath /dev/null 
#       --tlsAllowConnectionsWithoutCertificates
#       --tlsMode preferTLS
#       --tlsCertificateKeyFile /run/secrets/cert_db
#       --tlsCAFile /run/secrets/cert_db
#     secrets:
#       - cert_db
#       - pw
#     tmpfs:
#       - /data/db 
   
# secrets: 
#   pw: 
#     file: ./service/secrets/pw.txt
#   cert: 
#     file: ./service/secrets/cert.pem
#   key: 
#     file: ./service/secrets/key.pem
#   cert_db: 
#     file: ./service/secrets/server.pem
#   jwt_private_key:
#     file: ./service/secrets/private.pem
#   jwt_public_key:
#     file: ./service/secrets/public.pem
services:
  auction:
      build:
          context: ./service
          dockerfile: Dockerfile
      depends_on:
          - auction_db
      secrets:
          - auction_cert
          - auction_key
          - auction_pw
          - jwt_private_key
          - jwt_public_key

  auction_db:
      image: mongo:latest
      environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_DATABASE: admin
          MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/auction_pw
      command: mongod --quiet --logpath /dev/null
          --tlsAllowConnectionsWithoutCertificates
          --tlsMode preferTLS
          --tlsCertificateKeyFile /run/secrets/auction_cert_db
          --tlsCAFile /run/secrets/auction_cert_db
      secrets:
          - auction_cert_db
          - auction_pw
      volumes:
          - auction_db_data:/data/db

volumes:
  auction_db_data:
          driver: local

secrets:
    auction_pw:
        file: ./service/secrets/pw.txt
    auction_cert:
        file: ./service/secrets/cert.pem
    auction_key:
        file: ./service/secrets/key.pem
    auction_cert_db:
        file: ./service/secrets/server.pem
    jwt_private_key:
      file: ./service/secrets/private.pem
    jwt_public_key:
      file: ./service/secrets/public.pem