services:
    admin_nginx:
        container_name: admin_nginx
        image: nginx:latest
        environment:
            - NGINX_PORT=80
        volumes:
            - ${PWD}/gateways/admin/nginx:/etc/nginx/conf.d
        ports:
            - "8180:443"
        secrets:
            - ssl_admin_api_cert
            - ssl_admin_api_key
        networks:
            - gacha_private_network

secrets:
    ssl_admin_api_key:
        file: secrets/key.key
    ssl_admin_api_cert:
        file: secrets/cert.crt
