services:
  auction:
    restart: always
    build:
      context: ./auction_service/service
    networks:
      - gacha_network

  authentication:
    restart: always
    build:
      context: ./authentication_service/service
    networks:
      - gacha_network

  gacha-roll:
    restart: always
    build:
      context: ./gacha_service/service
    networks:
      - gacha_network

  payment:
    restart: always
    build:
      context: ./payment_service/service
    networks:
      - gacha_network

  user:
    restart: always
    build:
      context: ./user_service/service
    networks:
      - gacha_network

networks:
  gacha_network:
    driver: bridge
