services:
    tux_service:
        container_name: tux_service
        restart: no
        build:
            context: ./service
        environment:
            - TEST_RUN=true
        ports:
            - 9390:9090
        secrets:
            - jwt_public_key
            - ssl_private_key
            - ssl_cert
        networks:
            - gacha_network

secrets:
    jwt_public_key:
        file: ./service/secrets/public.pem
    ssl_private_key:
        file: ./service/secrets/key.pem
    ssl_cert:
        file: ./service/secrets/cert.pem

networks:
    gacha_network:
        driver: bridge
