services:
    tux_service:
        container_name: tux_service
        restart: unless-stopped
        build:
            context: ./service
        environment:
            - RESOURCE_PATH=/code/service/resources
        ports:
            - 9090:9090
        volumes:
            - ${PWD}/service:/code/service
        networks:
            - gacha_network

    tux_db:
        container_name: tux_db
        image: postgres
        restart: always
        shm_size: 128mb
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgres
        networks:
            - gacha_network

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.org
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_CONFIG_SERVER_MODE: "False"
        volumes:
            - ./pgadmin:/var/lib/pgadmin
        ports:
            - 5050:80
        networks:
            - gacha_network
        restart: unless-stopped

networks:
    gacha_network:
        driver: bridge
